##
# A callable workflow that runs PHP compatibility tests.
##
name: PHP Compatibility

on:
  workflow_call:

jobs:
  # Runs PHP compatibility testing.
  #
  # Violations are reported inline with annotations.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Sets up PHP.
  # - Logs debug information.
  # - Configures caching for PHP compatibility scans.
  # - Installs Composer dependencies.
  # - Make Composer packages available globally.
  # - Runs the PHP compatibility tests.
  # - Generate a report for displaying issues as pull request annotations.
  # - Ensures version-controlled files are not modified or deleted.
  php-compatibility:
    name: Run compatibility checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}

      - name: Set up PHP
        uses: shivammathur/setup-php@a4e22b60bbb9c1021113f2860347b0759f66fe5d # v2.30.0
        with:
          php-version: '7.4'
          coverage: none
          tools: cs2pr

      - name: Log debug information
        run: |
          composer --version

      # This date is used to ensure that the PHP compatibility cache is cleared at least once every week.
      # http://man7.org/linux/man-pages/man1/date.1.html
      - name: "Get last Monday's date"
        id: get-date
        run: echo "date=$(/bin/date -u --date='last Mon' "+%F")" >> $GITHUB_OUTPUT

      - name: Cache PHP compatibility scan cache
        uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319 # v4.0.1
        with:
          path: .cache/phpcompat.json
          key: ${{ runner.os }}-date-${{ steps.get-date.outputs.date }}-phpcompat-cache-${{ hashFiles('**/composer.json', 'phpcompat.xml.dist') }}

      # Since Composer dependencies are installed using `composer update` and no lock file is in version control,
      # passing a custom cache suffix ensures that the cache is flushed at least once per week.
      - name: Install Composer dependencies
        uses: ramsey/composer-install@57532f8be5bda426838819c5ee9afb8af389d51a # v3.0.0
        with:
          custom-cache-suffix: ${{ steps.get-date.outputs.date }}

      - name: Make Composer packages available globally
        run: echo "${PWD}/vendor/bin" >> $GITHUB_PATH

      - name: Run PHP compatibility tests
        id: phpcs
        run: phpcs --standard=phpcompat.xml.dist --report-full --report-checkstyle=./.cache/phpcs-compat-report.xml

      - name: Show PHPCompatibility results in PR
        if: ${{ always() && steps.phpcs.outcome == 'failure' }}
        run: cs2pr ./.cache/phpcs-compat-report.xml

      - name: Ensure version-controlled files are not modified or deleted
        run: git diff --exit-code
