##
# Performs follow-up tasks when a workflow fails or is cancelled.
##
name: Failed Workflow

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'ID of the GitHub Action workflow run to rerun'
        required: true
        type: 'string'

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  # Attempts to rerun a workflow.
  #
  # Performs the following steps:
  # - Retrieves the workflow run that dispatched this workflow.
  # - Restarts all failed jobs when the workflow fails or is cancelled for the first time.
  failed-workflow:
    name: Rerun a workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    timeout-minutes: 30

    steps:
      - name: Rerun a workflow
        uses: actions/github-script@e69ef5462fd455e02edcaf4dd7708eda96b9eda0 # v7.0.0
        with:
          retries: 15
          retry-exempt-status-codes: 418
          script: |
            const workflow_run = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ inputs.run_id }},
            });

            // Only rerun after the first run attempt.
            if ( workflow_run.data.run_attempt > 1 ) {
              return;
            }

            const rerun = await github.rest.actions.reRunWorkflowFailedJobs({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ inputs.run_id }},
              enable_debug_logging: true
            });
