name: Test NPM

on:
  push:
    branches:
      - trunk
      - '3.[7-9]'
      - '[4-9].[0-9]'
    tags:
      - '[0-9]+.[0-9]'
      - '[0-9]+.[0-9].[0-9]+'
  pull_request:
    branches:
      - trunk
      - '3.[7-9]'
      - '[4-9].[0-9]'
    paths:
      # These files configure NPM. Changes could affect the outcome.
      - 'package*.json'
      # JavaScript files are built using NPM.
      - '**.js'
      # CSS and SCSS files are built using NPM.
      - '**.scss'
      - '**.css'
      # Changes to workflow files should always verify all workflows are successful.
      - '.github/workflows/**.yml'
  workflow_dispatch:

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

env:
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: ${{ true }}

jobs:
  # Verifies that installing NPM dependencies and building WordPress works as expected.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Logs debug information about the GitHub Action runner.
  # - Installs NodeJS.
  # _ Installs NPM dependencies.
  # - Builds WordPress to run from the `build` directory.
  # - Cleans up after building WordPress to the `build` directory.
  # - Ensures version-controlled files are not modified or deleted.
  # - Builds WordPress to run from the `src` directory.
  # - Cleans up after building WordPress to the `src` directory.
  # - Ensures version-controlled files are not modified or deleted.
  test-npm:
    name: Test NPM on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    if: ${{ github.repository == 'WordPress/wordpress-develop' || github.event_name == 'pull_request' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Log debug information
        run: |
          npm --version
          node --version
          curl --version
          git --version
          svn --version

      - name: Install NodeJS
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.0
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build WordPress in /src
        run: npm run build:dev

      - name: Clean after building in /src
        run: npm run grunt clean -- --dev

      - name: Ensure version-controlled files are not modified or deleted during building and cleaning
        run: git diff --exit-code

      - name: Build WordPress
        run: npm run build

      - name: Clean after building
        run: npm run grunt clean

      - name: Ensure version-controlled files are not modified or deleted during building and cleaning
        run: git diff --exit-code

  # Verifies that installing NPM dependencies and building WordPress works as expected on MacOS.
  #
  # This is separate from the job above in order to use stricter conditions about when to run.
  # This avoids unintentionally consuming excessive minutes, as MacOS jobs consume minutes at a 10x rate.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Logs debug information about the GitHub Action runner.
  # - Installs NodeJS.
  # _ Installs NPM dependencies.
  # - Builds WordPress to run from the `build` directory.
  # - Cleans up after building WordPress to the `build` directory.
  # - Ensures version-controlled files are not modified or deleted.
  # - Builds WordPress to run from the `src` directory.
  # - Cleans up after building WordPress to the `src` directory.
  # - Ensures version-controlled files are not modified or deleted.
  test-npm-macos:
    name: Test NPM on MacOS
    runs-on: macos-latest
    timeout-minutes: 30
    if: ${{ github.repository == 'WordPress/wordpress-develop' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Log debug information
        run: |
          npm --version
          node --version
          curl --version
          git --version
          svn --version

      - name: Install NodeJS
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.0
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build WordPress in /src
        run: npm run build:dev

      - name: Clean after building in /src
        run: npm run grunt clean -- --dev

      - name: Ensure version-controlled files are not modified or deleted during building and cleaning
        run: git diff --exit-code

      - name: Build WordPress
        run: npm run build

      - name: Clean after building
        run: npm run grunt clean

      - name: Ensure version-controlled files are not modified or deleted during building and cleaning
        run: git diff --exit-code

  slack-notifications:
    name: Slack Notifications
    uses: WordPress/wordpress-develop/.github/workflows/slack-notifications.yml@trunk
    needs: [ test-npm, test-npm-macos ]
    if: ${{ github.repository == 'WordPress/wordpress-develop' && github.event_name != 'pull_request' && always() }}
    with:
      calling_status: ${{ needs.test-npm.result == 'success' && needs.test-npm-macos.result == 'success' && 'success' || ( needs.test-npm.result == 'cancelled' || needs.test-npm-macos.result == 'cancelled' ) && 'cancelled' || 'failure' }}
    secrets:
      SLACK_GHA_SUCCESS_WEBHOOK: ${{ secrets.SLACK_GHA_SUCCESS_WEBHOOK }}
      SLACK_GHA_CANCELLED_WEBHOOK: ${{ secrets.SLACK_GHA_CANCELLED_WEBHOOK }}
      SLACK_GHA_FIXED_WEBHOOK: ${{ secrets.SLACK_GHA_FIXED_WEBHOOK }}
      SLACK_GHA_FAILURE_WEBHOOK: ${{ secrets.SLACK_GHA_FAILURE_WEBHOOK }}

  failed-workflow:
    name: Failed workflow tasks
    runs-on: ubuntu-latest
    needs: [ test-npm, test-npm-macos, slack-notifications ]
    if: |
      always() &&
      github.repository == 'WordPress/wordpress-develop' &&
      github.event_name != 'pull_request' &&
      github.run_attempt < 2 &&
      (
        needs.test-npm.result == 'cancelled' || needs.test-npm.result == 'failure' ||
        needs.test-npm-macos.result == 'cancelled' || needs.test-npm-macos.result == 'failure'
      )

    steps:
      - name: Dispatch workflow run
        uses: actions/github-script@7dff1a87643417cf3b95bb10b29f4c4bc60d8ebd # v6.3.1
        with:
          retries: 2
          retry-exempt-status-codes: 418
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'failed-workflow.yml',
              ref: '${{ github.ref_name }}',
              inputs: {
                run_id: '${{ github.run_id }}'
              }
            });
